/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Wave.glb 
*/



import React, { useEffect, useRef } from 'react'
import { Canvas } from '@react-three/fiber';
import { useGLTF, useAnimations, OrbitControls } from '@react-three/drei'

const Action = (group,Animation) => {
  // const { actions } = useAnimations(Animation, group);

  // useEffect(() => {
  //   actions['Armature|mixamo.com|Layer0_Armature'].play();
  // }, [actions.Armature|mixamo.com|Layer0_Armature ]);
  // useEffect(() => {
  //   actions['Armature|mixamo.com|Layer0_Armature'].play();
  // }, [actions]);
}

const Wave = (props) => {
  const group = useRef()
  const { nodes, materials, Animation } = useGLTF('../src/assets/Wave.glb')
  
  // const { actions } = useAnimations(Animation, group);
  // console.log(actions)
  
  return (
    <Canvas>
    {/* <Action group={group} Animation={Animation}/> */}
    {/* <OrbitControls /> */}
    <directionalLight intensity={3}/>
    <ambientLight intensity={0.5}/>
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Boy01_Body_Geo" geometry={nodes.Boy01_Body_Geo.geometry} material={materials.Boy01_Body_MAT1} skeleton={nodes.Boy01_Body_Geo.skeleton} />
          <skinnedMesh name="Boy01_Brows_Geo" geometry={nodes.Boy01_Brows_Geo.geometry} material={materials.Boy01_Brows_MAT2} skeleton={nodes.Boy01_Brows_Geo.skeleton} />
          <skinnedMesh name="Boy01_Eyes_Geo" geometry={nodes.Boy01_Eyes_Geo.geometry} material={materials.Boy01_Eyes_MAT2} skeleton={nodes.Boy01_Eyes_Geo.skeleton} />
          <skinnedMesh name="h_Geo" geometry={nodes.h_Geo.geometry} material={materials.Boy01_Mouth_MAT2} skeleton={nodes.h_Geo.skeleton} />
        </group>
      </group>
    </group>
    
    </Canvas>
    
  )
  
}


export default Wave

useGLTF.preload('../src/assets/Wave.glb')
